[package]
name = "parser-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
fake-useragent = "0.1.3"
log = "0.4.22"
serde = "1.0.204"
sonic-rs = "0.3.8"

[dependencies.reqwest]
version = "0.12.5"
features = ["blocking", "json"]